#!/bin/bash

MONGO_HOST=localhost
MONGO_DB=date_a_bank_test
MONGO_PORT=27017
MONGO_TIMEOUT=500
COOKIE_SECRET="b to the dd"
TMP_PATH=/tmp

export MONGO_HOST MONGO_DB MONGO_PORT MONGO_TIMEOUT COOKIE_SECRET TMP_PATH

